---
- name: Install git and gitea
  tags: install
  block:
    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present

    - name: Create gitea user and group
      ansible.builtin.user:
        name: git
        shell: /sbin/nologin
        system: true
        create_home: false
        expires: -1

    - name: Download gitea binary
      ansible.builtin.get_url:
        dest: /usr/bin/gitea
        owner: root
        mode: "0755"
        url: "https://dl.gitea.com/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-{{ gitea_arch }}"

    - name: Deploy gitea directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        state: directory
        recurse: false
      loop:
        - { path: /var/lib/gitea, mode: "0750", owner: git, group: git }
        - { path: /var/lib/gitea/custom, mode: "0750", owner: git, group: git }
        - { path: /var/lib/gitea/data, mode: "0750", owner: git, group: git }
        - { path: /var/lib/gitea/log, mode: "0750", owner: git, group: git }
        - { path: /etc/gitea, mode: "0770", owner: root, group: git }
