---
- name: Install gitea
  ansible.builtin.include_tasks:
    file: "install/{{ gitea_source }}.yaml"

- name: Gitea configuration files
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - "conf/{{ gitea_source }}.yaml"
    - "conf/default.yaml"

- name: Gitea database initialization
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  with_first_found:
    - "database/{{ gitea_db_software }}.yaml"
    - "database/default.yaml"

- name: Expose gitea action runner token
  ansible.builtin.include_tasks:
    file: conf/act_runner_token.yaml
