gitea_db_host: # set me
gitea_db_port: # set me

# sqlite3, postgresql, mysql, mariadb
gitea_db_software: mysql

gitea_db_name: gitea
gitea_db_user: gitea
gitea_db_schema: gitea
gitea_db_password: # set me
